// This file is auto-generated by @hey-api/openapi-ts
export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/blankextension2/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];
export type ClientOptions = {
    baseUrl: 'https://localhost:44389' | (string & {});
};
